export const articlesData = [
    {
        id: 0,
        name: 'Pedro Fracno',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Plano de carreira e vagas em big Techs',
    },
    {
        id: 1,
        name: 'Mário monteiro',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: '5 Passos para fazer um design tal como está na UI sem sentir o exagero',
    },
    {
        id: 2,
        name: 'Flávio Coutinho',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Entenda o porquê VPN com internet grátis só funciona com rede Africell',
    },
    {
        id: 3,
        name: 'Inácio Raimundo',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: '5 Passos para fazer um design tal como está na UI sem sentir o exagero',
    },
    {
        id: 4,
        name: 'Lázaro Manuel',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Criando componentes e simples Hooks personalizados com javascript puro',
    },
    {
        id: 5,
        name: 'Lito Bumba',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Entenda o porquê VPN com internet grátis só funciona com rede Africell',
    },
    {
        id: 6,
        name: 'Lázaro Manuel',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Criando componentes e simples Hooks personalizados com javascript puro',
    },
    {
        id: 7,
        name: 'Lito Bumba',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Entenda o porquê VPN com internet grátis só funciona com rede Africell',
    },
    {
        id: 8,
        name: 'Lito Bumba',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Entenda o porquê VPN com internet grátis só funciona com rede Africell',
    },
    {
        id: 9,
        name: 'Lázaro Manuel',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Criando componentes e simples Hooks personalizados com javascript puro',
    },
    {
        id: 10,
        name: 'Lito Bumba',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Entenda o porquê VPN com internet grátis só funciona com rede Africell',
    },
    {
        id: 11,
        name: 'Lito Bumba',
        avatarURL: './images/unidos.jpg',
        articleImg: './images/unidos.jpg',
        availableAt: new Date(),
        title: 'Entenda o porquê VPN com internet grátis só funciona com rede Africell',
    }
]